stack_size = {
    'wood': 99,
    'rock': 99,
    'branch': 99,
    'campfire': 10,
    'furnace': 10,
    'pickaxe': 1,
    'iron-ore': 99,
    'iron-bar': 99,
    'grass':99
}

colors = {
    'purple': (142, 32, 167)
}

crafting = {
    'campfire': [('wood', 5), ('branch', 10)],
    'furnace': [('rock', 10), ('wood', 20)]
}

entity_data = {
    'god': {
        'action': 'gather',
        'modifier': 5
    },
    'furnace': {
        'name': 'furnace',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [0, 0],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'pickaxe': 1},
        'yield': [('furnace', (1, 1), 100)],
        'is_barrier': True,
        'is_pickupable': True,
        'action': 'place',
        'crafting': {
            'iron-bar': [('iron-ore', 2)]
        },
        'height': 0,
        'type': 'entity'
    },
    'pickaxe': {
        'name': 'pickaxe',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [0, 0],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'hand': 1},
        'yield': [('pickaxe', (1, 1), 100)],
        'is_barrier': False,
        'is_pickupable': True,
        'action': 'gather',
        'height': 0,
        'type': 'entity'
    },
    'campfire': {
        'name': 'campfire',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [0, 0],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'axe': 1, 'hand': 2},
        'yield': [('campfire', (1, 1), 100)],
        'is_barrier': True,
        'is_pickupable': True,
        'is_light_source': True,
        'animations': ['campfire-idle'],
        'animation-duration': {'campfire-idle': 10},
        'action': 'place',
        'height': 10,
        'type': 'entity'
    },
    'tree': {
        'name': 'tree',
        'size': [32, 32],
        'rect_size': [12, 12],
        'rect_offset': [10, 20],
        'world_offset': [5, 5],
        'gather_time': {'god': .1, 'axe': 1, 'hand': 2},
        'yield': [('wood', (8, 12), 20), ('wood', (4, 8), 100)],
        'is_barrier': True,
        'is_pickupable': True,
        'action': None,
        'height': 10,
        'type': 'entity'
    },
    'branch': {
        'name': 'branch',
        'size': [16, 16],
        'rect_size': [14, 14],
        'rect_offset': [1, 1],
        'world_offset': [2, 2],
        'gather_time': {'god': .1, 'hand': 1},
        'yield': [('branch', (3, 4), 20), ('branch', (1, 2), 100)],
        'is_barrier': False,
        'is_pickupable': True,
        'action': None,
        'height': 0,
        'type': 'entity'
    },
    'wood': {
        'name': 'wood',
        'size': [15, 5],
        'rect_size': [15, 5],
        'rect_offset': [0, 0],
        'world_offset': [0, 10],
        'gather_time': {'god': .1, 'axe': 1},
        'yield': [('wood', (1, 1), 100)],
        'is_barrier': False,
        'is_pickupable': True,
        'action': None,
        'height': 0,
        'type': 'entity'
    },
    'rock': {
        'name': 'rock',
        'size': [15, 5],
        'rect_size': [15, 5],
        'rect_offset': [0, 0],
        'world_offset': [0, 10],
        'gather_time': {'god': .1, 'pickaxe': 1},
        'yield': [('rock', (1, 1), 100)],
        'is_barrier': False,
        'is_pickupable': True,
        'action': None,
        'height': 0,
        'type': 'entity'
    },
    'iron-ore': {
        'name': 'iron-ore',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [0, 0],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'hand': .5},
        'yield': [('iron-ore', (1, 1), 100)],
        'is_barrier': False,
        'is_pickupable': True,
        'action': None,
        'height': 0,
        'type': 'entity'
    },
    'iron-bar': {
        'name': 'iron-bar',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [0, 0],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'hand': .5},
        'yield': [('iron-bar', (1, 1), 100)],
        'is_barrier': False,
        'is_pickupable': True,
        'action': None,
        'height': 0,
        'type': 'entity'
    },
    'iron-ore-1': {
        'name': 'iron-ore',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [0, 0],
        'world_offset': [0, 10],
        'gather_time': {'god': .1, 'pickaxe': 1},
        'yield': [('iron-ore', (1, 1), 100)],
        'is_barrier': True,
        'is_pickupable': True,
        'action': None,
        'height': 10,
        'type': 'entity'
    },
    'rock-1': {
        'name': 'rock',
        'size': [15, 5],
        'rect_size': [15, 5],
        'rect_offset': [0, 0],
        'world_offset': [0, 10],
        'gather_time': {'god': .1, 'pickaxe': 1},
        'yield': [('rock', (1, 1), 100)],
        'is_barrier': True,
        'is_pickupable': True,
        'action': None,
        'height': 10,
        'type': 'entity'
    },
    'rock-2': {
        'name': 'rock',
        'size': [20, 10],
        'rect_size': [20, 10],
        'rect_offset': [0, 0],
        'world_offset': [0, 5],
        'gather_time': {'god': .1, 'pickaxe': 2},
        'yield': [('rock', (3, 4), 50), ('rock', (1, 2), 100)],
        'is_barrier': True,
        'is_pickupable': True,
        'action': None,
        'height': 10,
        'type': 'entity'
    },
    'rock-3': {
        'name': 'rock',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [0, 0],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'pickaxe': 2},
        'yield': [('rock', (4, 5), 50), ('rock', (2, 3), 100)],
        'is_barrier': True,
        'is_pickupable': True,
        'action': None,
        'height': 0,
        'type': 'entity'
    },
    'water': {
        'name': 'water',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [0, 0],
        'world_offset': [0, 0],
        'gather_time': {},
        'yield': [],
        'is_barrier': True,
        'is_pickupable': False,
        'action': None,
        'height': 0,
        'type': 'tile'
    },
    'sand': {
        'name': 'sand',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [2, 2],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'hand': 2, 'shovel': 1},
        'yield': [('sand', (1, 1), 100)],
        'is_barrier': False,
        'is_pickupable': False,
        'action': None,
        'height': 10,
        'type': 'tile'
    },
    'grass': {
        'name': 'grass',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [2, 2],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'hand': 2, 'shovel': 1},
        'yield': [('grass', (1, 1), 100)],
        'is_barrier': False,
        'is_pickupable': False,
        'action': 'place',
        'height': 20,
        'type': 'tile'
    },
    'dirt': {
        'name': 'dirt',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [2, 2],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'hand': 2, 'shovel': 1},
        'yield': [('dirt', (1, 1), 100)],
        'is_barrier': False,
        'is_pickupable': False,
        'action': None,
        'height': 30,
        'type': 'tile'
    },
    'stone': {
        'name': 'stone',
        'size': [16, 16],
        'rect_size': [16, 16],
        'rect_offset': [0, 0],
        'world_offset': [0, 0],
        'gather_time': {'god': .1, 'pickaxe': 2},
        'yield': [('stone', (1, 1), 100)],
        'is_barrier': False,
        'is_pickupable': False,
        'action': None,
        'height': 25,
        'type': 'tile'
    },
}
